apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://kubeflow.develop.pe.underdogsports.com/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: false
    connectors:
    - type: oidc
      id: okta
      name: Okta
      config:
        issuer: https://underdogsports.okta.com/oauth2/default
        clientID: 0oatdb0yzheg9hu6S697
        clientSecret: RdZ-Mvq615hErZBCdG53Y5uaTi-WZ61eHPl1fFha_mskHx2AZiOpJjfu4VlmO_HV
        redirectURI: https://kubeflow.develop.pe.underdogsports.com/dex/callback
        scopes:
        - openid
        - email
        - profile
    staticClients:
    - id: kubeflow-oidc-authservice
      redirectURIs:
      - '/oauth2/callback'
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
