apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - ../../base

patchesStrategicMerge:
  - config-map-patch.yaml

configMapGenerator:
  - name: dex-env
    behavior: merge
    envs:
      - secret_params.env
