apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    ad.datadoghq.com/service.check_names: '["istio"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: '[{"istio_mesh_endpoint": "http://%%host%%:15020/stats/prometheus", "use_openmetrics": true}]'
spec:
  type: ClusterIP
  ports:
    - name: http-monitoring
      port: 15020
      protocol: TCP
      targetPort: 15020
