apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/istio-external-auth

configMapGenerator:
  - name: oauth2-proxy
    behavior: replace
    files:
      - oauth2_proxy.cfg
